[parse]
net_name = "bert"
framework = "pytorch"
inputs = [[1, 32, 768],[1,32],[1,32]]
inputs_layout = "FD;FD;FD"
pre_method = "nop;nop;nop"
pre_scale = "nop;nop;nop"
pre_mean = "nop;nop;nop"
channel_swap = "nop;nop;nop"
network = "../2_compile/fmodel/bert_traced.pt"
jr_path = "../3_deploy/modelzoo/bert_cls/imodel/8/"
frame_version = "1.9"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/bert_cls/imodel/8/bert_parsed.json"
raw = "../3_deploy/modelzoo/bert_cls/imodel/8/bert_parsed.raw"
jr_path = "../3_deploy/modelzoo/bert_cls/imodel/8/"

[quantize]
forward_mode = "image"
saturation = "null"
forward_dir = "./qtset/bert"
forward_list = "./qtset/bert.txt "
bits = 8
json = "../3_deploy/modelzoo/bert_cls/imodel/8/bert_optimized.json"
raw = "../3_deploy/modelzoo/bert_cls/imodel/8/bert_optimized.raw"
jr_path = "../3_deploy/modelzoo/bert_cls/imodel/8/"
per = "tensor"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/bert_cls/imodel/8/bert_quantized.json"
raw = "../3_deploy/modelzoo/bert_cls/imodel/8/bert_quantized.raw"
jr_path = "../3_deploy/modelzoo/bert_cls/imodel/8/"

[generate]
json = "../3_deploy/modelzoo/bert_cls/imodel/8/bert_adapted.json"
raw = "../3_deploy/modelzoo/bert_cls/imodel/8/bert_adapted.raw"
# jr_path = "../3_deploy/modelzoo/bert_cls/imodel/8/"
jr_path = "../3_deploy/modelzoo/bert_cls/imodel/8/"
log_path = "./logs/"

