[parse]
net_name = "SLBAF"
framework = "pytorch"
inputs = [[1, 480, 640, 3], [1, 480, 640, 3]]
inputs_layout = "NHWC;NHWC"
pre_method = "nop;nop"
pre_scale = "nop;nop"
pre_mean  = "nop;nop"
channel_swap = "nop;nop"
network = "./fmodel/slbaf.pt"
jr_path = "../3_deploy/modelzoo/SLBAF-Net/imodel/8/"
frame_version = "1.9"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/SLBAF-Net/imodel/8/SLBAF_parsed.json"
raw = "../3_deploy/modelzoo/SLBAF-Net/imodel/8/SLBAF_parsed.raw"
jr_path = "../3_deploy/modelzoo/SLBAF-Net/imodel/8/"

[quantize]
forward_mode = "image"
saturation = "kld"
forward_dir = "./qtset/test"
forward_list = "./qtset/test.txt"
bits = 8
json = "../3_deploy/modelzoo/SLBAF-Net/imodel/8/SLBAF_optimized.json"
raw = "../3_deploy/modelzoo/SLBAF-Net/imodel/8/SLBAF_optimized.raw"
jr_path = "../3_deploy/modelzoo/SLBAF-Net/imodel/8/"
per = "channel"
target = "buyi"
no_transinput = true

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/SLBAF-Net/imodel/8/SLBAF_quantized.json"
raw = "../3_deploy/modelzoo/SLBAF-Net/imodel/8/SLBAF_quantized.raw"
jr_path = "../3_deploy/modelzoo/SLBAF-Net/imodel/8/"

[generate]
json = "../3_deploy/modelzoo/SLBAF-Net/imodel/8/SLBAF_adapted.json"
raw = "../3_deploy/modelzoo/SLBAF-Net/imodel/8/SLBAF_adapted.raw"
jr_path = "../3_deploy/modelzoo/SLBAF-Net/imodel/8/"
log_path = "./logs/"

[run]
log_time = true
log_io = true
dump_format = "SFB"
json = "../3_deploy/modelzoo/SLBAF-Net/imodel/8/SLBAF_parsed.json"
raw = "../3_deploy/modelzoo/SLBAF-Net/imodel/8/SLBAF_parsed.raw"
input = "./qtset/SLBAF/ir.bin;./qtset/SLBAF/vi.bin"