[parse]
net_name = "siamfc++-net-1"
framework = "pytorch"
inputs = [ 1, 127, 127, 3]
inputs_layout = "NHWC"
pre_method = "nop"
#post_method = "nop"
pre_scale = [ 1.0, 1.0, 1.0]
pre_mean = [ 0.0, 0.0, 0.0]
channel_swap = [ 0, 1, 2]
network = "./fmodel/siamfc++-net-1-127x127.pt"
jr_path = "../3_deploy/modelzoo/siamfc++/imodel/8_siamfc++_net1/"
frame_version = "1.9"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/siamfc++/imodel/8_siamfc++_net1/siamfc++-net-1_parsed.json"
raw = "../3_deploy/modelzoo/siamfc++/imodel/8_siamfc++_net1/siamfc++-net-1_parsed.raw"
jr_path = "../3_deploy/modelzoo/siamfc++/imodel/8_siamfc++_net1/"

[quantize]
forward_mode = "image"
saturation = "kld"
forward_dir = "./qtset/coco"
forward_list = "./qtset/coco.txt"
bits = 8
json = "../3_deploy/modelzoo/siamfc++/imodel/8_siamfc++_net1/siamfc++-net-1_optimized.json"
raw = "../3_deploy/modelzoo/siamfc++/imodel/8_siamfc++_net1/siamfc++-net-1_optimized.raw"
jr_path = "../3_deploy/modelzoo/siamfc++/imodel/8_siamfc++_net1/"
per = "channel"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/siamfc++/imodel/8_siamfc++_net1/siamfc++-net-1_quantized.json"
raw = "../3_deploy/modelzoo/siamfc++/imodel/8_siamfc++_net1/siamfc++-net-1_quantized.raw"
jr_path = "../3_deploy/modelzoo/siamfc++/imodel/8_siamfc++_net1/"
pass_on =  "customop.ImageMakePass"
custom_config = "./config/customop/yolov5_warpaffine.toml"

[generate]
json = "../3_deploy/modelzoo/siamfc++/imodel/8_siamfc++_net1/siamfc++-net-1_adapted.json"
raw = "../3_deploy/modelzoo/siamfc++/imodel/8_siamfc++_net1/siamfc++-net-1_adapted.raw"
jr_path = "../3_deploy/modelzoo/siamfc++/imodel/8_siamfc++_net1/"
log_path = "./logs/"
no_mergeops = true
etmopt = 0
