[parse]
net_name = "tardal_dt"
framework = "pytorch"
inputs = [[1, 768, 1024, 1], [1, 768, 1024, 1]]
inputs_layout = "NHWC;NHWC"
pre_method = "nop;nop"
pre_scale = "nop;nop"
pre_mean  = "nop;nop"
channel_swap = "nop;nop"
network = "./fmodel/tardal-dt.pt"
jr_path = "../3_deploy/modelzoo/TarDAL/imodel/16/"
frame_version = "1.9"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/TarDAL/imodel/16/tardal_dt_parsed.json"
raw = "../3_deploy/modelzoo/TarDAL/imodel/16/tardal_dt_parsed.raw"
jr_path = "../3_deploy/modelzoo/TarDAL/imodel/16/"

[quantize]
forward_mode = "image"
saturation = "kld"
forward_dir = "./qtset/tardal_dt"
forward_list = "./qtset/tardal_dt.txt"
bits = 16
json = "../3_deploy/modelzoo/TarDAL/imodel/16/tardal_dt_optimized.json"
raw = "../3_deploy/modelzoo/TarDAL/imodel/16/tardal_dt_optimized.raw"
jr_path = "../3_deploy/modelzoo/TarDAL/imodel/16/"
per = "channel"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/TarDAL/imodel/16/tardal_dt_quantized.json"
raw = "../3_deploy/modelzoo/TarDAL/imodel/16/tardal_dt_quantized.raw"
jr_path = "../3_deploy/modelzoo/TarDAL/imodel/16/"

[generate]
json = "../3_deploy/modelzoo/TarDAL/imodel/16/tardal_dt_adapted.json"
raw = "../3_deploy/modelzoo/TarDAL/imodel/16/tardal_dt_adapted.raw"
jr_path = "../3_deploy/modelzoo/TarDAL/imodel/16/"
log_path = "./logs/"

[run]
log_time = true
log_io = true
dump_format = "SFB"
json = "../3_deploy/modelzoo/TarDAL/imodel/16/tardal_dt_parsed.json"
raw = "../3_deploy/modelzoo/TarDAL/imodel/16/tardal_dt_parsed.raw"
input = "./qtset/tardal_dt/ir.bin;./qtset/tardal_dt/vi.bin"