
  # "p": "parsed",
  # "o": "optimized",
  # "q": "quantized",
  # "a": "adapted",
  # "g": "BY",
imodel: 
  cudamode: false  
  mmu: true
  speedmode: false
  compressFtmp: false
  net_dir: ../imodel/8/
  stage: g
  sim: False
  ip: 192.168.125.185
  save: true
  show: true
  calctime: true
 
dataset:
  dir: ../io/input/test_p00/
  res: ../io/output/test_p00/

param:
  test_id: 0  # person_id
  batch_size: 1 
  dataloader:
    num_workers: 1
    pin_memory: False

camera:
  do: true
  camerah: 1080
  cameraw: 1920