[parse]
net_name = "yolov9t"
framework = "pytorch"
frame_version = "1.9"
inputs = [1, 640, 640, 3]
inputs_layout = "NHWC"
pre_method = "resize"
pre_scale = [255.0, 255.0, 255.0]
pre_mean = [0.0, 0.0, 0.0]
channel_swap = [0, 1, 2]
network = "fmodel/yolov9t_640x640.pt"
jr_path = "../3_deploy/modelzoo/yolov9/imodel/8/"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/yolov9/imodel/8/yolov9t_parsed.json"
raw = "../3_deploy/modelzoo/yolov9/imodel/8/yolov9t_parsed.raw"
jr_path = "../3_deploy/modelzoo/yolov9/imodel/8/"

[quantize]
forward_mode = "image" 
saturation = "kld"
forward_dir = "./qtset/coco"
forward_list = "./qtset/coco.txt "
batch = 1
bits = 8
json = "../3_deploy/modelzoo/yolov9/imodel/8/yolov9t_optimized.json"
raw = "../3_deploy/modelzoo/yolov9/imodel/8/yolov9t_optimized.raw"
jr_path = "../3_deploy/modelzoo/yolov9/imodel/8/"
per = "channel"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/yolov9/imodel/8/yolov9t_quantized.json"
raw = "../3_deploy/modelzoo/yolov9/imodel/8/yolov9t_quantized.raw"
jr_path = "../3_deploy/modelzoo/yolov9/imodel/8/"
pass_on =  "customop.ImageMakePass,customop.DetPostPass"
custom_config = "config/customop/yolov9.toml"

[generate]
json = "../3_deploy/modelzoo/yolov9/imodel/8/yolov9t_adapted.json"
raw = "../3_deploy/modelzoo/yolov9/imodel/8/yolov9t_adapted.raw"
jr_path = "../3_deploy/modelzoo/yolov9/imodel/8/"

[run]
log_time = true
log_io = true
dump_format = "SFB"
json = "../3_deploy/modelzoo/yolov9/imodel/8/yolov9t_parsed.json"
raw = "../3_deploy/modelzoo/yolov9/imodel/8/yolov9t_parsed.raw"
input = "./qtset/coco/horses.ftmp"

