[parse]
net_name = "nafnet_A_selfattn"
framework = "pytorch"
inputs = [ 1, 736, 1280, 3]
inputs_layout = "NHWC"
pre_method = "nop"
pre_scale = [ 255.0, 255.0, 255.0]
pre_mean = [ 0.0, 0.0, 0.0]
channel_swap = [ 0, 1, 2]
network = "fmodel/self_A_attn_736x1280.pt"
jr_path = "../3_deploy/modelzoo/nafnet_lite/imodel/8/"
frame_version = "1.9"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/nafnet_lite/imodel/8/nafnet_A_selfattn_parsed.json"
raw = "../3_deploy/modelzoo/nafnet_lite/imodel/8/nafnet_A_selfattn_parsed.raw"
jr_path = "../3_deploy/modelzoo/nafnet_lite/imodel/8/"

[quantize]
forward_mode = "image"
saturation = "kld"
forward_dir = "./qtset/blur"
forward_list = "./qtset/blur.txt"
bits = 8
json = "../3_deploy/modelzoo/nafnet_lite/imodel/8/nafnet_A_selfattn_optimized.json"
raw = "../3_deploy/modelzoo/nafnet_lite/imodel/8/nafnet_A_selfattn_optimized.raw"
jr_path = "../3_deploy/modelzoo/nafnet_lite/imodel/8/"
per = "channel"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/nafnet_lite/imodel/8/nafnet_A_selfattn_quantized.json"
raw = "../3_deploy/modelzoo/nafnet_lite/imodel/8/nafnet_A_selfattn_quantized.raw"
jr_path = "../3_deploy/modelzoo/nafnet_lite/imodel/8/"
pass_on =  "customop.ImageMakePass"
custom_config = "config/customop/nafnet.toml"

[generate]
json = "../3_deploy/modelzoo/nafnet_lite/imodel/8/nafnet_A_selfattn_adapted.json"
raw = "../3_deploy/modelzoo/nafnet_lite/imodel/8/nafnet_A_selfattn_adapted.raw"
jr_path = "../3_deploy/modelzoo/nafnet_lite/imodel/8/"
log_path = "./logs/"

[run]
log_time = true
log_io = true
dump_format = "SFB"
json = "../3_deploy/modelzoo/nafnet_lite/imodel/8/nafnet_A_selfattn_BY.json"
raw = ".../3_deploy/modelzoo/nafnet_lite/imodel/8/nafnet_A_selfattn_BY.raw"
input = "./qtset/coco/bus.jpg"
log_path = "./logs/"
