[parse]
net_name = "SFA3D"
framework = "pytorch"
inputs = [1, 608, 608, 3]
inputs_layout = "NHWC"
pre_method = "nop"
pre_scale = "nop"
pre_mean = "nop"
channel_swap = "nop"
#pre_scale = "58.395,57.12,57.375;58.395,57.12,57.375"
#pre_mean = "123.675,116.28,103.53;123.675,116.28,103.53"
#channel_swap = "2,1,0;2,1,0"
network = "./fmodel/sfa3d.pt"
jr_path = "../3_deploy/modelzoo/SFA3D/imodel/8/"
frame_version = "1.9"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/SFA3D/imodel/8/sfa3d_parsed.json"
raw = "../3_deploy/modelzoo/SFA3D/imodel/8/sfa3d_parsed.raw"
jr_path = "../3_deploy/modelzoo/SFA3D/imodel/8/"

[quantize]
forward_mode = "image"
saturation = "kld"
forward_dir = "./qtset/kitti"
forward_list = "./qtset/sfa3d.txt"
bits = 8
json = "../3_deploy/modelzoo/SFA3D/imodel/8/sfa3d_optimized.json"
raw = "../3_deploy/modelzoo/SFA3D/imodel/8/sfa3d_optimized.raw"
jr_path = "../3_deploy/modelzoo/SFA3D/imodel/8/"
per = "channel"
target = "buyi"
no_transinput = true

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/SFA3D/imodel/8/sfa3d_quantized.json"
raw = "../3_deploy/modelzoo/SFA3D/imodel/8/sfa3d_quantized.raw"
jr_path = "../3_deploy/modelzoo/SFA3D/imodel/8/"

[generate]
json = "../3_deploy/modelzoo/SFA3D/imodel/8/sfa3d_adapted.json"
raw = "../3_deploy/modelzoo/SFA3D/imodel/8/sfa3d_adapted.raw"
jr_path = "../3_deploy/modelzoo/SFA3D/imodel/8/"
log_path = "./logs/"

