[parse]
net_name = "mixformerv2_small"
framework = "pytorch"
inputs = [[ 1, 3, 112, 112], [1, 3, 112, 112], [1, 3, 224, 224], [1, 196, 768], [1,49,768], [1,4,768]]
inputs_layout = "FD;FD;FD;FD;FD;FD"
pre_method = "nop;nop;nop;nop;nop;nop"
pre_scale = "nop;nop;nop;nop;nop;nop"
pre_mean = "nop;nop;nop;nop;nop;nop"
channel_swap = "nop;nop;nop;nop;nop;nop"
network = "fmodel/mixformer2_vit_online_small_1x3x224x224_traced.pt"
jr_path = "../3_deploy/modelzoo/MixformerV2/imodel/8/"
frame_version = "1.9"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/MixformerV2/imodel/8/mixformerv2_small_parsed.json"
raw = "../3_deploy/modelzoo/MixformerV2/imodel/8/mixformerv2_small_parsed.raw"
jr_path = "../3_deploy/modelzoo/MixformerV2/imodel/8/"
pass_on = "icraft.InputFoldPass"
pass_off="icraft.ConvertSlice2SplitPass"
custom_config = "config/customop/mixformer_foldparams.toml"


[quantize]
forward_mode = "image"
saturation = "null"
forward_dir = "./qtset/mixformerv2-small-5seqs_per100"
forward_list = "./qtset/mixformerv2-small-5seqs_per100-three.txt"
bits = 8
json = "../3_deploy/modelzoo/MixformerV2/imodel/8/mixformerv2_small_optimized.json"
raw = "../3_deploy/modelzoo/MixformerV2/imodel/8/mixformerv2_small_optimized.raw"
jr_path = "../3_deploy/modelzoo/MixformerV2/imodel/8/"
per = "tensor"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/MixformerV2/imodel/8/mixformerv2_small_quantized.json"
raw = "../3_deploy/modelzoo/MixformerV2/imodel/8/mixformerv2_small_quantized.raw"
jr_path = "../3_deploy/modelzoo/MixformerV2/imodel/8/"


[generate]
json = "../3_deploy/modelzoo/MixformerV2/imodel/8/mixformerv2_small_adapted.json"
raw = "../3_deploy/modelzoo/MixformerV2/imodel/8/mixformerv2_small_adapted.raw"
jr_path = "../3_deploy/modelzoo/MixformerV2/imodel/8/"
log_path = "./logs/"



