[parse]
net_name = "ae"
framework = "pytorch"
inputs = [1,3,80,160]
inputs_layout = "FD"
pre_method = "nop"
pre_scale = "nop"
pre_mean = "nop"
channel_swap = "nop"
network = "./fmodel/ae.pt"
jr_path = "../3_deploy/modelzoo/donkey_car/imodel/16/"
frame_version = "1.9"


[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/donkey_car/imodel/16/ae_parsed.json"
raw = "../3_deploy/modelzoo/donkey_car/imodel/16/ae_parsed.raw"
jr_path = "../3_deploy/modelzoo/donkey_car/imodel/16/"

[quantize]
forward_mode = "image"
saturation = "kld"
forward_dir = "./qtset/images"
forward_list = "./qtset/list.txt"
bits = 16
json = "../3_deploy/modelzoo/donkey_car/imodel/16/ae_optimized.json"
raw = "../3_deploy/modelzoo/donkey_car/imodel/16/ae_optimized.raw"
jr_path = "../3_deploy/modelzoo/donkey_car/imodel/16/"
per = "channel"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/donkey_car/imodel/16/ae_quantized.json"
raw = "../3_deploy/modelzoo/donkey_car/imodel/16/ae_quantized.raw"
jr_path = "../3_deploy/modelzoo/donkey_car/imodel/16/"


[generate]
json = "../3_deploy/modelzoo/donkey_car/imodel/16/ae_adapted.json"
raw = "../3_deploy/modelzoo/donkey_car/imodel/16/ae_adapted.raw"
jr_path = "../3_deploy/modelzoo/donkey_car/imodel/16/"
log_path = "logs/"

