[parse]
net_name ="PPyoloe_crn_s"
framework = "Onnx"
inputs = [1, 640, 640, 3]
inputs_layout = "NHWC"
pre_method = "resize"
pre_scale = [255.0, 255.0, 255.0]
pre_mean = [0.0, 0.0, 0.0]
channel_swap = [0, 1, 2]
network = "fmodel/ppyoloe_plus_crn_s_80e_coco_640x640.onnx"
jr_path = "../3_deploy/modelzoo/ppyoloe/imodel/16/"


[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/ppyoloe/imodel/16/PPyoloe_crn_s_parsed.json"
raw = "../3_deploy/modelzoo/ppyoloe/imodel/16/PPyoloe_crn_s_parsed.raw"
jr_path = "../3_deploy/modelzoo/ppyoloe/imodel/16/"

[quantize]
forward_mode = "image"
saturation = "kld"
forward_dir = "./qtset/coco"
forward_list = "./qtset/coco.txt"
bits = 16
json = "../3_deploy/modelzoo/ppyoloe/imodel/16/PPyoloe_crn_s_optimized.json"
raw = "../3_deploy/modelzoo/ppyoloe/imodel/16/PPyoloe_crn_s_optimized.raw"
jr_path = "../3_deploy/modelzoo/ppyoloe/imodel/16/"
per = "tensor"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/ppyoloe/imodel/16/PPyoloe_crn_s_quantized.json"
raw = "../3_deploy/modelzoo/ppyoloe/imodel/16/PPyoloe_crn_s_quantized.raw"
jr_path = "../3_deploy/modelzoo/ppyoloe/imodel/16/"
pass_on =  "customop.ImageMakePass,customop.DetPostPass"
custom_config = "config/customop/ppyoloe.toml"

[generate]
json = "../3_deploy/modelzoo/ppyoloe/imodel/16/PPyoloe_crn_s_adapted.json"
raw = "../3_deploy/modelzoo/ppyoloe/imodel/16/PPyoloe_crn_s_adapted.raw"
jr_path = "../3_deploy/modelzoo/ppyoloe/imodel/16/"
log_path = "./logs/"

[run]
log_time = true
log_io = true
dump_ftmp = "SFB"
json = "../3_deploy/modelzoo/ppyoloe/imodel/16/PPyoloe_crn_s_BY.json"
raw = "../3_deploy/modelzoo/yolov6/imodel/16/PPyoloe_crn_s_BY.raw"
input = "./qtset/coco/000000000139.jpg"
log_path = "./logs/"


