[parse]
net_name = "pointnet"
framework = "pytorch"
frame_version = "1.9"
inputs = [1,3,1024]
inputs_layout = "FD"
pre_method = "nop"
pre_scale = "nop"
pre_mean = "nop"
channel_swap ="nop"
network = "./fmodel/pointnet_traced_3x1024.pt"
jr_path = "../3_deploy/modelzoo/pointnet/imodel/16/"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/pointnet/imodel/16/pointnet_parsed.json"
raw = "../3_deploy/modelzoo/pointnet/imodel/16/pointnet_parsed.raw"
jr_path = "../3_deploy/modelzoo/pointnet/imodel/16/"
pass_off = "icraft.ConvertInnerProduct2Conv2dPass"

[quantize]
forward_mode = "image" 
saturation = "kld"
forward_dir = "./qtset/modelnet40_ftmp"
forward_list = "./qtset/modelnet40_ftmp.txt"
batch = 1
bits = 16
json = "../3_deploy/modelzoo/pointnet/imodel/16/pointnet_optimized.json"
raw = "../3_deploy/modelzoo/pointnet/imodel/16/pointnet_optimized.raw"
jr_path = "../3_deploy/modelzoo/pointnet/imodel/16/"
per = "channel"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/pointnet/imodel/16/pointnet_quantized.json"
raw = "../3_deploy/modelzoo/pointnet/imodel/16/pointnet_quantized.raw"
jr_path = "../3_deploy/modelzoo/pointnet/imodel/16/"

[generate]
json = "../3_deploy/modelzoo/pointnet/imodel/16/pointnet_adapted.json"
raw = "../3_deploy/modelzoo/pointnet/imodel/16/pointnet_adapted.raw"
jr_path = "../3_deploy/modelzoo/pointnet/imodel/16/"


[run]
log_time = true
log_io = true
dump_format = "SFB"
json = "../3_deploy/modelzoo/pointnet/imodel/16/pointnet_BY.json"
raw = "../3_deploy/modelzoo/pointnet/imodel/16/pointnet_BY.raw"
input = "./qtset/ftmp/airplane_0627.ftmp"
log_path = "./logs/"
backends = "BY,socket://ql100aiu@192.168.124.134:9981?npu=0x40000000&dma=0x80000000;Host"

