[parse]
net_name = "bert_mask"
framework = "pytorch"
inputs = [[1, 128, 768], [1, 128],[1, 128]]
inputs_layout = "FD;FD;FD"
pre_method = "nop;nop;nop"
pre_scale = "nop;nop;nop"
pre_mean = "nop;nop;nop"
channel_swap = "nop;nop;nop"
network = "../2_compile/fmodel/bert_mask_traced.pt"
jr_path = "./imodel/16/"
frame_version = "1.9"

[optimize]
target = "BUYI"
json = "./imodel/16/bert_mask_parsed.json"
raw = "./imodel/16/bert_mask_parsed.raw"
jr_path = "./imodel/16/"

[quantize]
forward_mode = "image"
saturation = "null"
forward_dir = "./qtset/bert"
forward_list = "./qtset/bert.txt "
bits = 16
json = "./imodel/16/bert_mask_optimized.json"
raw = "./imodel/16/bert_mask_optimized.raw"
jr_path = "./imodel/16/"
per = "tensor"
target = "buyi"

[adapt]
target = "BUYI"
json = "./imodel/16/bert_mask_quantized.json"
raw = "./imodel/16/bert_mask_quantized.raw"
jr_path = "./imodel/16/"

[generate]
json = "./imodel/16/bert_mask_adapted.json"
raw = "./imodel/16/bert_mask_adapted.raw"
jr_path = "../3_deploy/modelzoo/bert/imodel/16/"
log_path = "./logs/"

[run]
log_time = true
log_io = true
dump_format = "SFB"
json = "../3_deploy/modelzoo/bert/imodel/16/bert_mask_BY.json"
raw = "../3_deploy/modelzoo/bert/imodel/16/bert_mask_BY.raw"
input = "./qtset/bert/embedding_out.ftmp;./qtset/bert/input_ids.ftmp;./qtset/bert/attention_mask.ftmp"
log_path = "./logs/"
backends = "BY,socket://ql100aiu@192.168.125.183:9981?npu=0x40000000&dma=0x80000000;Host"
