[parse]
net_name = "TextCNN"
framework = "pytorch"
inputs = [1, 32, 300]
inputs_layout = "FD"
pre_method = "nop"
pre_scale = "nop"
pre_mean = "nop"
channel_swap = "nop"
network = "../2_compile/fmodel/TextCNN_traced.pt"
jr_path = "./imodel/8/"
frame_version = "1.9"

[optimize]
target = "BUYI"
json = "./imodel/8/TextCNN_parsed.json"
raw = "./imodel/8/TextCNN_parsed.raw"
jr_path = "./imodel/8/"

[quantize]
forward_mode = "image"
saturation = "null"
forward_dir = "./qtset/TextCNN"
forward_list = "./qtset/TextCNN.txt "
bits = 8
json = "./imodel/8/TextCNN_optimized.json"
raw = "./imodel/8/TextCNN_optimized.raw"
jr_path = "./imodel/8/"
per = "tensor"
target = "buyi"

[adapt]
target = "BUYI"
json = "./imodel/8/TextCNN_quantized.json"
raw = "./imodel/8/TextCNN_quantized.raw"
jr_path = "./imodel/8/"

[generate]
json = "./imodel/8/TextCNN_adapted.json"
raw = "./imodel/8/TextCNN_adapted.raw"
# jr_path = "./imodel/8/"
jr_path = "../3_deploy/modelzoo/TextCNN/imodel/8/"
log_path = "./logs/"

