[parse]
net_name = "yolov7-w6-pose"
framework = "pytorch"
inputs = [ 1, 640, 640, 3]
inputs_layout = "NHWC"
pre_method = "resize"
pre_scale = [ 255, 255, 255]
pre_mean = [ 0, 0, 0]
channel_swap = [ 0, 1, 2]
network = "fmodel/yolov7-w6-pose-640x640.pt"
jr_path = "../3_deploy/modelzoo/yolov7_pose/imodel/16/"
frame_version = "1.9"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/yolov7_pose/imodel/16/yolov7-w6-pose_parsed.json"
raw = "../3_deploy/modelzoo/yolov7_pose/imodel/16/yolov7-w6-pose_parsed.raw"
jr_path = "../3_deploy/modelzoo/yolov7_pose/imodel/16/"

[quantize]
forward_mode = "image"
saturation = "kld"
forward_dir = "./qtset/coco"
forward_list = "./qtset/coco.txt"
bits = 16
json = "../3_deploy/modelzoo/yolov7_pose/imodel/16/yolov7-w6-pose_optimized.json"
raw = "../3_deploy/modelzoo/yolov7_pose/imodel/16/yolov7-w6-pose_optimized.raw"
jr_path = "../3_deploy/modelzoo/yolov7_pose/imodel/16/"
per = "tensor"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/yolov7_pose/imodel/16/yolov7-w6-pose_quantized.json"
raw = "../3_deploy/modelzoo/yolov7_pose/imodel/16/yolov7-w6-pose_quantized.raw"
jr_path = "../3_deploy/modelzoo/yolov7_pose/imodel/16/"
pass_on =  "customop.ImageMakePass,customop.DetPostPass"
custom_config = "config/customop/yolov7-w6-pose.toml"

[generate]
json = "../3_deploy/modelzoo/yolov7_pose/imodel/16/yolov7-w6-pose_adapted.json"
raw = "../3_deploy/modelzoo/yolov7_pose/imodel/16/yolov7-w6-pose_adapted.raw"
jr_path = "../3_deploy/modelzoo/yolov7_pose/imodel/16/"
log_path = "./logs/"

[simulate]
log_time = true
log_io = true
dump_ftmp = "SFB"
show = true
json = "../3_deploy/modelzoo/yolov7_pose/imodel/16/yolov7-w6-pose_BY.json"
raw = "../3_deploy/modelzoo/yolov7_pose/imodel/16/yolov7-w6-pose_BY.raw"
image = "./qtset/bus640.jpg"
target = "BUYI"
log_path = "./logs/"
