_BASE_: [
  './datasets/coco_detection.yml',
  './runtime.yml',
  './_base_/optimizer_80e.yml',
  './_base_/ppyoloe_plus_crn.yml',
  './_base_/ppyoloe_plus_reader.yml',
]

log_iter: 100
snapshot_epoch: 5
weights: ../weights/ppyoloe_plus_crn_s_80e_coco.pdparams

# pretrain_weights: ../weights/CSPResNetb_s_pretrained2.pdparams
depth_mult: 0.33
width_mult: 0.50
