[parse]
net_name = "superpoint-1200x1600"
framework = "pytorch"
inputs = [ 1, 1200, 1600, 1]
inputs_layout = "NHWC"
pre_method = "nop"
#post_method = "nop"
pre_scale = [ 255.0 ]
pre_mean = [ 0.0 ]
channel_swap = [ 0]
network = "./fmodel/superpoint-1200x1600.pt"
jr_path = "../3_deploy/modelzoo/superglue/imodel/superpoint-1200x1600/"
frame_version = "1.9"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/superglue/imodel/superpoint-1200x1600/superpoint-1200x1600_parsed.json"
raw = "../3_deploy/modelzoo/superglue/imodel/superpoint-1200x1600/superpoint-1200x1600_parsed.raw"
jr_path = "../3_deploy/modelzoo/superglue/imodel/superpoint-1200x1600/"

[quantize]
forward_mode = "image"
saturation = "kld"
forward_dir = "./qtset/superpoint"
forward_list = "./qtset/superpoint.txt"
bits = 8
json = "../3_deploy/modelzoo/superglue/imodel/superpoint-1200x1600/superpoint-1200x1600_optimized.json"
raw = "../3_deploy/modelzoo/superglue/imodel/superpoint-1200x1600/superpoint-1200x1600_optimized.raw"
jr_path = "../3_deploy/modelzoo/superglue/imodel/superpoint-1200x1600/"
decode_dll = "./config/customop/customop.SingleChannelDecoder.dll"
per = "tensor"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/superglue/imodel/superpoint-1200x1600/superpoint-1200x1600_quantized.json"
raw = "../3_deploy/modelzoo/superglue/imodel/superpoint-1200x1600/superpoint-1200x1600_quantized.raw"
pass_on =  "icraft.AddReshape2Output1Pass,customop.ImageMakePass"
custom_config = "./config/customop/superglue_config.toml"
jr_path = "../3_deploy/modelzoo/superglue/imodel/superpoint-1200x1600/"

[generate]
json = "../3_deploy/modelzoo/superglue/imodel/superpoint-1200x1600/superpoint-1200x1600_adapted.json"
raw = "../3_deploy/modelzoo/superglue/imodel/superpoint-1200x1600/superpoint-1200x1600_adapted.raw"
jr_path = "../3_deploy/modelzoo/superglue/imodel/superpoint-1200x1600/"
log_path = "./logs/"

[run]
log_time = true
log_io = true
dump_format = "SFB"
json = "../3_deploy/modelzoo/superglue/imodel/superpoint-1200x1600/superpoint-1200x1600_BY.json"
raw = "../3_deploy/modelzoo/superglue/imodel/superpoint-1200x1600/superpoint-1200x1600_BY.raw"
input = "./qtset/superpoint/00172642_6310427717.jpg"
backends = "BY,socket://ql100aiu@192.168.125.183:9981?npu=0x40000000&dma=0x80000000;Host"
# backends = "Host"
