[parse]
net_name = "PolyLaneNet"
framework = "pytorch"
frame_version = "1.9"
inputs = [1,360,640,3]
inputs_layout = "NHWC"
pre_method = "resize"
pre_scale = [ 58.395, 57.12, 57.375]
pre_mean = [123.675, 116.28, 103.53]
channel_swap =[0, 1, 2]
network = "./fmodel/PolyLaneNet_360x640.pt"
jr_path = "../3_deploy/modelzoo/PolyLaneNet/imodel/8/"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/PolyLaneNet/imodel/8/PolyLaneNet_parsed.json"
raw = "../3_deploy/modelzoo/PolyLaneNet/imodel/8/PolyLaneNet_parsed.raw"
jr_path = "../3_deploy/modelzoo/PolyLaneNet/imodel/8/"

[quantize]
forward_mode = "image" 
saturation = "kld"
forward_dir = "./qtset/tuSimple"
forward_list = "./qtset/tuSimple.txt"
batch = 1
bits = 8
json = "../3_deploy/modelzoo/PolyLaneNet/imodel/8/PolyLaneNet_optimized.json"
raw = "../3_deploy/modelzoo/PolyLaneNet/imodel/8/PolyLaneNet_optimized.raw"
jr_path = "../3_deploy/modelzoo/PolyLaneNet/imodel/8/"
per = "channel"
target = "buyi"
mix_precision = "auto"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/PolyLaneNet/imodel/8/PolyLaneNet_quantized.json"
raw = "../3_deploy/modelzoo/PolyLaneNet/imodel/8/PolyLaneNet_quantized.raw"
jr_path = "../3_deploy/modelzoo/PolyLaneNet/imodel/8/"
pass_on =  "customop.ImageMakePass"
custom_config = "config/customop/PolyLaneNet.toml"

[generate]
json = "../3_deploy/modelzoo/PolyLaneNet/imodel/8/PolyLaneNet_adapted.json"
raw = "../3_deploy/modelzoo/PolyLaneNet/imodel/8/PolyLaneNet_adapted.raw"
jr_path = "../3_deploy/modelzoo/PolyLaneNet/imodel/8/"

[run]
log_time = true
log_io = true
dump_format = "SFB"
json = "../3_deploy/modelzoo/PolyLaneNet/imodel/8/PolyLaneNet_BY.json"
raw = "../3_deploy/modelzoo/PolyLaneNet/imodel/8/PolyLaneNet_BY.raw"
input = "./qtset/tuSimple/10.jpg"
backends = "BY,socket://ql100aiu@192.168.125.184:9981?npu=0x40000000&dma=0x80000000;Host"
