[parse]
net_name = "MPIIGaze"
framework = "onnx"
inputs = [[ 1, 1, 36, 60],[1,2]]
inputs_layout = "FD;FD"
pre_method = "nop;nop"
pre_scale = "nop;nop"
pre_mean = "nop;nop"
channel_swap = "nop;nop"
network = "fmodel/MPIIGaze_1x1x36x60_1x2.onnx"
jr_path = "../3_deploy/modelzoo/MPIIGaze/imodel/16/"
#frame_version = "1.9"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/MPIIGaze/imodel/16/MPIIGaze_parsed.json"
raw = "../3_deploy/modelzoo/MPIIGaze/imodel/16/MPIIGaze_parsed.raw"
jr_path = "../3_deploy/modelzoo/MPIIGaze/imodel/16/"

[quantize]
forward_mode = "image"
saturation = "null"
forward_dir = "./qtset/MPIIGaze"
forward_list = "./qtset/MPIIGaze.txt"
bits = 16
json = "../3_deploy/modelzoo/MPIIGaze/imodel/16/MPIIGaze_optimized.json"
raw = "../3_deploy/modelzoo/MPIIGaze/imodel/16/MPIIGaze_optimized.raw"
jr_path = "../3_deploy/modelzoo/MPIIGaze/imodel/16/"
per = "tensor"
target = "buyi"
no_imagemake = true
no_transinput = true

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/MPIIGaze/imodel/16/MPIIGaze_quantized.json"
raw = "../3_deploy/modelzoo/MPIIGaze/imodel/16/MPIIGaze_quantized.raw"
jr_path = "../3_deploy/modelzoo/MPIIGaze/imodel/16/"
#pass_on =  "customop.ImageMakePass"
#custom_config = "config/customop/yolox.toml"

[generate]
json = "../3_deploy/modelzoo/MPIIGaze/imodel/16/MPIIGaze_adapted.json"
raw = "../3_deploy/modelzoo/MPIIGaze/imodel/16/MPIIGaze_adapted.raw"
jr_path = "../3_deploy/modelzoo/MPIIGaze/imodel/16/"
log_path = "./logs/"

[run]
log_time = true
log_io = true
dump_format = "SFB"
json = "../3_deploy/modelzoo/MPIIGaze/imodel/16/MPIIGaze_BY.json"
raw = "../3_deploy/modelzoo/MPIIGaze/imodel/16/MPIIGaze_BY.raw"
input = "./qtset/coco/bus.jpg"
log_path = "./logs/"
