[parse]
net_name = "siamrpn++_net1"
framework = "pytorch"
inputs = [ 1, 127, 127, 3]
inputs_layout = "NHWC"
pre_method = "nop"
#post_method = "nop"
pre_scale = [ 1.0, 1.0, 1.0]
pre_mean = [ 0.0, 0.0, 0.0]
channel_swap = [ 0, 1, 2]
network = "./fmodel/siamrpn++-net-1-127x127.pt"
jr_path = "../3_deploy/modelzoo/siamrpn++/imodel/8_siamrpn++_net1/"
frame_version = "1.9"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/siamrpn++/imodel/8_siamrpn++_net1/siamrpn++_net1_parsed.json"
raw = "../3_deploy/modelzoo/siamrpn++/imodel/8_siamrpn++_net1/siamrpn++_net1_parsed.raw"
jr_path = "../3_deploy/modelzoo/siamrpn++/imodel/8_siamrpn++_net1/"

[quantize]
forward_mode = "image"
saturation = "kld"
forward_dir = "./qtset/coco"
forward_list = "./qtset/coco.txt"
bits = 8
json = "../3_deploy/modelzoo/siamrpn++/imodel/8_siamrpn++_net1/siamrpn++_net1_optimized.json"
raw = "../3_deploy/modelzoo/siamrpn++/imodel/8_siamrpn++_net1/siamrpn++_net1_optimized.raw"
jr_path = "../3_deploy/modelzoo/siamrpn++/imodel/8_siamrpn++_net1/"
per = "tensor"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/siamrpn++/imodel/8_siamrpn++_net1/siamrpn++_net1_quantized.json"
raw = "../3_deploy/modelzoo/siamrpn++/imodel/8_siamrpn++_net1/siamrpn++_net1_quantized.raw"
jr_path = "../3_deploy/modelzoo/siamrpn++/imodel/8_siamrpn++_net1/"
pass_on =  "customop.ImageMakePass"
custom_config = "./config/customop/siamrpn++.toml"

[generate]
json = "../3_deploy/modelzoo/siamrpn++/imodel/8_siamrpn++_net1/siamrpn++_net1_adapted.json"
raw = "../3_deploy/modelzoo/siamrpn++/imodel/8_siamrpn++_net1/siamrpn++_net1_adapted.raw"
jr_path = "../3_deploy/modelzoo/siamrpn++/imodel/8_siamrpn++_net1/"

