[parse]
net_name = "mimo-unet_720x1280"
framework = "pytorch"
inputs = [ 1, 720, 1280, 3]
inputs_layout = "NHWC"
pre_method = "nop"
pre_scale = [ 255.0, 255.0, 255.0]
pre_mean = [ 0.0, 0.0, 0.0]
channel_swap = [ 0, 1, 2]
network = "fmodel/mimo-unet_720x1280.pt"
jr_path = "../3_deploy/modelzoo/mimo-unet/imodel/16/"
frame_version = "1.9"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/mimo-unet/imodel/16/mimo-unet_720x1280_parsed.json"
raw = "../3_deploy/modelzoo/mimo-unet/imodel/16/mimo-unet_720x1280_parsed.raw"
jr_path = "../3_deploy/modelzoo/mimo-unet/imodel/16/"

[quantize]
forward_mode = "image"
saturation = "kld"
forward_dir = "./qtset/blur"
forward_list = "./qtset/blur.txt"
bits = 16
json = "../3_deploy/modelzoo/mimo-unet/imodel/16/mimo-unet_720x1280_optimized.json"
raw = "../3_deploy/modelzoo/mimo-unet/imodel/16/mimo-unet_720x1280_optimized.raw"
jr_path = "../3_deploy/modelzoo/mimo-unet/imodel/16/"
per = "channel"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/mimo-unet/imodel/16/mimo-unet_720x1280_quantized.json"
raw = "../3_deploy/modelzoo/mimo-unet/imodel/16/mimo-unet_720x1280_quantized.raw"
jr_path = "../3_deploy/modelzoo/mimo-unet/imodel/16/"
pass_on =  "customop.ImageMakePass"
custom_config = "config/customop/mimo-unet.toml"

[generate]
json = "../3_deploy/modelzoo/mimo-unet/imodel/16/mimo-unet_720x1280_adapted.json"
raw = "../3_deploy/modelzoo/mimo-unet/imodel/16/mimo-unet_720x1280_adapted.raw"
jr_path = "../3_deploy/modelzoo/mimo-unet/imodel/16/"
log_path = "./logs/"
# ocmopt = "0"

[run]
log_time = true
log_io = true
dump_format = "SFB"
json = "../3_deploy/modelzoo/mimo-unet/imodel/16/mimo-unet_720x1280_BY.json"
raw = "../3_deploy/modelzoo/mimo-unet/imodel/16/mimo-unet_720x1280_BY.raw"
input = "./qtset/blur/GOPR0384_11_00-000001.png"
log_path = "./logs/"
