[parse]
net_name = "DDRNet_SegPost"
framework = "pytorch"
inputs = [ 1, 1024, 2048, 3]
inputs_layout = "NHWC"
pre_method = "resize"
#post_method = "nop"
pre_scale = [ 58.395, 57.12, 57.375]
pre_mean = [ 123.675, 116.28, 103.53]
channel_swap = [ 0, 1, 2]
network = "fmodel/DDRNet_1024x2048_traced.pt"
jr_path = "../3_deploy/modelzoo/DDRNet/imodel/segpost/"
frame_version = "1.9"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/DDRNet/imodel/segpost/DDRNet_SegPost_parsed.json"
raw = "../3_deploy/modelzoo/DDRNet/imodel/segpost/DDRNet_SegPost_parsed.raw"
jr_path = "../3_deploy/modelzoo/DDRNet/imodel/segpost/"


[quantize]
forward_mode = "image"
saturation = "kld"
forward_dir = "./qtset/cityscapes"
forward_list = "./qtset/cityscapes.txt"
bits = 8
json = "../3_deploy/modelzoo/DDRNet/imodel/segpost/DDRNet_SegPost_optimized.json"
raw = "../3_deploy/modelzoo/DDRNet/imodel/segpost/DDRNet_SegPost_optimized.raw"
jr_path = "../3_deploy/modelzoo/DDRNet/imodel/segpost/"
per = "channel"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/DDRNet/imodel/segpost/DDRNet_SegPost_quantized.json"
raw = "../3_deploy/modelzoo/DDRNet/imodel/segpost/DDRNet_SegPost_quantized.raw"
jr_path = "../3_deploy/modelzoo/DDRNet/imodel/segpost/"
pass_on =  "customop.ImageMakePass,customop.SegPostPass"
custom_config = "config/customop/DDRNet.toml"


[generate]
json = "../3_deploy/modelzoo/DDRNet/imodel/segpost/DDRNet_SegPost_adapted.json"
raw = "../3_deploy/modelzoo/DDRNet/imodel/segpost/DDRNet_SegPost_adapted.raw"
jr_path = "../3_deploy/modelzoo/DDRNet/imodel/segpost/"
# rows = "2"
# cols = "2"


[run]
log_time = true
#log_io = true
dump_format = "SFB"
json = "../3_deploy/modelzoo/DDRNet/imodel/segpost/DDRNet_SegPost_BY.json"
raw = "../3_deploy/modelzoo/DDRNet/imodel/segpost/DDRNet_SegPost_BY.raw"
input = "./qtset/cityscapes/frankfurt_000000_000294_leftImg8bit.png"
# backends = "BY,socket://ql100aiu@192.168.125.237:9981?npu=0x40000000&dma=0x80000000;Host"
log_path = "./logs/"

