[parse]
net_name = "yolox_s_plin"
framework = "pytorch"
inputs = [ 1, 512, 960, 3]
inputs_layout = "NHWC"
pre_method = "resize"
pre_scale = [ 1.0, 1.0, 1.0]
pre_mean = [ 0.0, 0.0, 0.0]
channel_swap = [ 2, 1, 0]
network = "fmodel/yolox_s_512x960_traced.pt"
jr_path = "../3_deploy/modelzoo/yolox/imodel/plin/"
frame_version = "1.9"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/yolox/imodel/plin/yolox_s_plin_parsed.json"
raw = "../3_deploy/modelzoo/yolox/imodel/plin/yolox_s_plin_parsed.raw"
jr_path = "../3_deploy/modelzoo/yolox/imodel/plin/"

[quantize]
forward_mode = "image"
saturation = "kld"
forward_dir = "./qtset/coco"
forward_list = "./qtset/coco.txt"
bits = 8
json = "../3_deploy/modelzoo/yolox/imodel/plin/yolox_s_plin_optimized.json"
raw = "../3_deploy/modelzoo/yolox/imodel/plin/yolox_s_plin_optimized.raw"
jr_path = "../3_deploy/modelzoo/yolox/imodel/plin/"
per = "tensor"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/yolox/imodel/plin/yolox_s_plin_quantized.json"
raw = "../3_deploy/modelzoo/yolox/imodel/plin/yolox_s_plin_quantized.raw"
jr_path = "../3_deploy/modelzoo/yolox/imodel/plin/"
pass_on =  "customop.ImageMakePass,customop.DetPostPass"
custom_config = "config/customop/yolox.toml"

[generate]
json = "../3_deploy/modelzoo/yolox/imodel/plin/yolox_s_plin_adapted.json"
raw = "../3_deploy/modelzoo/yolox/imodel/plin/yolox_s_plin_adapted.raw"
jr_path = "../3_deploy/modelzoo/yolox/imodel/plin/"
log_path = "./logs/"
no_mergeops = true
etmopt = 0

[run]
log_time = true
log_io = true
dump_format = "SFB"
json = "../3_deploy/modelzoo/yolox/imodel/plin/yolox_s_plin_BY.json"
raw = "../3_deploy/modelzoo/yolox/imodel/plin/yolox_s_plin_BY.raw"
input = "./qtset/coco/bus.jpg"
log_path = "./logs/"
