[parse]
net_name = "gelan_c_pan"
framework = "pytorch"
frame_version = "1.9"
inputs = [ 1, 640, 640, 3]
inputs_layout = "NHWC"
pre_method = "resize"
pre_scale = [ 255.0, 255.0, 255.0]
pre_mean = [ 0.0, 0.0, 0.0]
channel_swap = [ 0, 1, 2]
network = "fmodel/gelan-c-pan-640x640.pt"
jr_path = "../3_deploy/modelzoo/yolov9_pan/imodel/16/"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/yolov9_pan/imodel/16/gelan_c_pan_parsed.json"
raw = "../3_deploy/modelzoo/yolov9_pan/imodel/16/gelan_c_pan_parsed.raw"
jr_path = "../3_deploy/modelzoo/yolov9_pan/imodel/16/"

[quantize]
forward_mode = "image"
saturation = "null"
forward_dir = "./qtset/coco"
forward_list = "./qtset/coco.txt"
batch = 1
bits = 16
json = "../3_deploy/modelzoo/yolov9_pan/imodel/16/gelan_c_pan_optimized.json"
raw = "../3_deploy/modelzoo/yolov9_pan/imodel/16/gelan_c_pan_optimized.raw"
jr_path = "../3_deploy/modelzoo/yolov9_pan/imodel/16/"
per = "channel"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/yolov9_pan/imodel/16/gelan_c_pan_quantized.json"
raw = "../3_deploy/modelzoo/yolov9_pan/imodel/16/gelan_c_pan_quantized.raw"
jr_path = "../3_deploy/modelzoo/yolov9_pan/imodel/16/"
pass_on =  "customop.ImageMakePass,customop.DetPostPass"
custom_config = "config/customop/gelan_c_pan.toml"

[generate]
json = "../3_deploy/modelzoo/yolov9_pan/imodel/16/gelan_c_pan_adapted.json"
raw = "../3_deploy/modelzoo/yolov9_pan/imodel/16/gelan_c_pan_adapted.raw"
jr_path = "../3_deploy/modelzoo/yolov9_pan/imodel/16/"
log_path = "./logs/"

[run]
log_time = true
log_io = true
dump_format = "SFB"
json = "../3_deploy/modelzoo/yolov9_pan/imodel/16/gelan_c_pan_BY.json"
raw = ".../3_deploy/modelzoo/yolov9_pan/imodel/16/gelan_c_pan_BY.raw"
input = "./qtset/coco/bus.jpg"
log_path = "./logs/"
