[parse]
net_name = "Yolo11s"
framework = "pytorch"
frame_version = "1.9"
inputs = [1, 640, 640, 3]
inputs_layout = "NHWC"
pre_method = "resize"
pre_scale = [255.0, 255.0, 255.0]
pre_mean = [0.0, 0.0, 0.0]
channel_swap = [0, 1, 2]
network = "fmodel/yolo11s_640x640.pt"
jr_path = "../3_deploy/modelzoo/yolo11/imodel/8/"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/yolo11/imodel/8/yolo11s_parsed.json"
raw = "../3_deploy/modelzoo/yolo11/imodel/8/yolo11s_parsed.raw"
jr_path = "../3_deploy/modelzoo/yolo11/imodel/8/"

[quantize]
forward_mode = "image" 
saturation = "ems"
forward_dir = "./qtset/coco"
forward_list = "./qtset/coco.txt "
batch = 1
bits = 8
json = "../3_deploy/modelzoo/yolo11/imodel/8/yolo11s_optimized.json"
raw = "../3_deploy/modelzoo/yolo11/imodel/8/yolo11s_optimized.raw"
jr_path = "../3_deploy/modelzoo/yolo11/imodel/8/"
per = "channel"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/yolo11/imodel/8/yolo11s_quantized.json"
raw = "../3_deploy/modelzoo/yolo11/imodel/8/yolo11s_quantized.raw"
jr_path = "../3_deploy/modelzoo/yolo11/imodel/8/"
pass_on =  "customop.ImageMakePass,customop.DetPostPass"
custom_config = "config/customop/yolo11s.toml"

[generate]
json = "../3_deploy/modelzoo/yolo11/imodel/8/yolo11s_adapted.json"
raw = "../3_deploy/modelzoo/yolo11/imodel/8/yolo11s_adapted.raw"
jr_path = "../3_deploy/modelzoo/yolo11/imodel/8/"
log_path = "./logs/"

[run]
log_time = true
log_io = true
dump_format = "SFB"
json = "../3_deploy/modelzoo/yolo11/imodel/8/yolo11s_BY.json"
raw = "../3_deploy/modelzoo/yolo11/imodel/8/yolo11s_BY.raw"
input = "./qtset/coco/bus.jpg"
log_path = "./logs/"

