mode: MPIIGaze
device: cpu
model:
  name: resnet_preact
gaze_estimator:
  checkpoint: ../../../../weights/mpiigaze_resnet_preact.pth #data/models/mpiigaze/resnet_preact/model.pth
  camera_params: ../../../../0_MPIIGaze/data/calib/sample_params.yaml
  normalized_camera_params: ../../../../0_MPIIGaze/data/calib/normalized_camera_params_eye.yaml
  normalized_camera_distance: 0.6
demo:
  use_camera: False
  display_on_screen: True
  wait_time: 1
  video_path: '../io/input/imgs/image00.jpg' #'./data/video/kid.mp4'
  output_dir: ''
  output_file_extension: mp4
  head_pose_axis_length: 0.05
  gaze_visualization_length: 0.05
  show_bbox: True
  show_head_pose: True
  show_landmarks: True
  show_normalized_image: False
  show_template_model: False
