[parse]
net_name = "yolov8s_seg"
framework = "pytorch"
inputs = [ 1, 640, 640, 3]
inputs_layout = "NHWC"
pre_method = "resize"
pre_scale = [ 255.0, 255.0, 255.0]
pre_mean = [ 0.0, 0.0, 0.0]
channel_swap = [ 0, 1, 2]
network = "fmodel/yolov8s-seg-640x640.pt"
jr_path = "../3_deploy/modelzoo/yolov8_seg/imodel/8/"
frame_version = "1.9"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/yolov8_seg/imodel/8/yolov8s_seg_parsed.json"
raw = "../3_deploy/modelzoo/yolov8_seg/imodel/8/yolov8s_seg_parsed.raw"
jr_path = "../3_deploy/modelzoo/yolov8_seg/imodel/8/"

[quantize]
forward_mode = "image"
saturation = "kld"
forward_dir = "./qtset/coco"
forward_list = "./qtset/coco.txt"
bits = 8
json = "../3_deploy/modelzoo/yolov8_seg/imodel/8/yolov8s_seg_optimized.json"
raw = "../3_deploy/modelzoo/yolov8_seg/imodel/8/yolov8s_seg_optimized.raw"
jr_path = "../3_deploy/modelzoo/yolov8_seg/imodel/8/"
per = "channel"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/yolov8_seg/imodel/8/yolov8s_seg_quantized.json"
raw = "../3_deploy/modelzoo/yolov8_seg/imodel/8/yolov8s_seg_quantized.raw"
jr_path = "../3_deploy/modelzoo/yolov8_seg/imodel/8/"
pass_on =  "customop.ImageMakePass,customop.DetPostPass"
custom_config = "config/customop/yolov8s_seg_customop.toml"

[generate]
json = "../3_deploy/modelzoo/yolov8_seg/imodel/8/yolov8s_seg_adapted.json"
raw = "../3_deploy/modelzoo/yolov8_seg/imodel/8/yolov8s_seg_adapted.raw"
jr_path = "../3_deploy/modelzoo/yolov8_seg/imodel/8/"
log_path = "./logs/"

[run]
log_time = true
log_io = true
dump_format = "SFB"
json = "../3_deploy/modelzoo/yolov8_seg/imodel/8/yolov8s_seg_BY.json"
raw = ".../3_deploy/modelzoo/yolov8_seg/imodel/8/yolov8s_seg_BY.raw"
input = "./qtset/coco/bus.jpg"
log_path = "./logs/"
