[parse]
net_name = "HybridNets"
framework = "onnx"
inputs = [ 1, 384, 640, 3]
inputs_layout = "NHWC"
pre_method = "resize"
pre_scale = [[ 58.395, 57.12, 57.375]]
pre_mean = [[ 123.675, 116.28, 103.53]]
channel_swap = [[0, 1, 2]] #rgb
network = "./fmodel/HybridNets_1x3x384x640_traced.onnx"
jr_path = "../3_deploy/modelzoo/HybridNets/imodel/8/"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/HybridNets/imodel/8/HybridNets_parsed.json"
raw = "../3_deploy/modelzoo/HybridNets/imodel/8/HybridNets_parsed.raw"
jr_path = "../3_deploy/modelzoo/HybridNets/imodel/8/"

[quantize]
forward_mode = "image"
saturation = "ems"
forward_dir = "./qtset/HybridNets/"
forward_list = "./qtset/HybridNets.txt"
bits = 8
json = "../3_deploy/modelzoo/HybridNets/imodel/8/HybridNets_optimized.json"
raw = "../3_deploy/modelzoo/HybridNets/imodel/8/HybridNets_optimized.raw"
jr_path = "../3_deploy/modelzoo/HybridNets/imodel/8/"
per = "tensor"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/HybridNets/imodel/8/HybridNets_quantized.json"
raw = "../3_deploy/modelzoo/HybridNets/imodel/8/HybridNets_quantized.raw"
jr_path = "../3_deploy/modelzoo/HybridNets/imodel/8/"
pass_on =  "customop.ImageMakePass"
custom_config = "config/customop/HybridNets.toml"

[generate]
json = "../3_deploy/modelzoo/HybridNets/imodel/8/HybridNets_adapted.json"
raw = "../3_deploy/modelzoo/HybridNets/imodel/8/HybridNets_adapted.raw"
jr_path = "../3_deploy/modelzoo/HybridNets/imodel/8/"
no_mergeops = true
etmopt = 0
ocmopt = 0


[run]
log_time = true
log_io = true
dump_format = "SFB"
json = "../3_deploy/modelzoo/HybridNets/imodel/8/HybridNets_BY.json"
raw = "../3_deploy/modelzoo/HybridNets/imodel/8/HybridNets_BY.raw"
input = "./qtset/HybridNets/test_1.jpg"
#backends = "BY,socket://ql100aiu@192.168.125.185:9981?npu=0x40000000&dma=0x80000000;Host"
